extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  '@typescript-eslint/no-unnecessary-condition': off
  '@typescript-eslint/prefer-nullish-coalescing': off

  import/no-extraneous-dependencies: off

  jsdoc/require-jsdoc: off

  n/no-extraneous-import: off
  n/no-unsupported-features/es-syntax: off
  n/no-unsupported-features/node-builtins: off
