name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx eslint .

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npm run prepack
      - run: npm run build --workspaces

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npm pack

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx prettier --check .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx tsc

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run prepack
      - run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  # release:
  #   runs-on: ubuntu-latest
  #   needs: [eslint, pack, prettier, tsc]
  #   if: startsWith(github.ref, 'refs/tags/')
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with: { node-version: 16 }
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
