name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npm pack

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npm run lint

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx tsc
